# Generated by Django 6.0.4 on 2026-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(choices=[('weak_topic', 'Weak Topic Improvement'), ('weak_topic_resource', 'Weak Topic Resource'), ('spaced_repetition', 'Spaced Repetition Review'), ('trending', 'Trending Content'), ('exam_relevant', 'Exam Relevant'), ('performance_based', 'Based on Performance'), ('interest_based', 'Based on Interests'), ('adaptive', 'Adaptive Difficulty'), ('daily_goal', 'Daily Goal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('pdf', 'PDF'), ('video', 'Video'), ('article', 'Article / Reference Site'), ('note', 'Note'), ('mock_test', 'Mock Test'), ('revision', 'Revision'), ('exam_update', 'Exam Update'), ('practice', 'Practice Set')], max_length=50),
        ),
    ]
