# Generated by Django 6.0.4 on 2026-05-19 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevisionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='mcq', max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(max_length=500)),
                ('user_answer', models.CharField(blank=True, default='', max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('reference', models.TextField(blank=True, default='')),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('source_quiz_id', models.IntegerField(blank=True, null=True)),
                ('source_quiz_title', models.CharField(blank=True, default='', max_length=300)),
                ('is_revised', models.BooleanField(default=False)),
                ('revised_correctly', models.BooleanField(default=False)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revision_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_daily_revision_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'date', 'is_revised'], name='rec_daily_r_user_id_82200a_idx')],
            },
        ),
    ]
