# Generated by Django 6.0.4 on 2026-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_dailyrevisionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='marks_allotted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='patterns',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='topics_to_cover',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
