# Generated by Django 6.0.3 on 2026-03-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Central Govt', 'Central Govt'), ('State Govt', 'State Govt'), ('PSU', 'PSU'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Management', 'Management'), ('Defence', 'Defence'), ('Banking', 'Banking'), ('Other', 'Other')], max_length=50)),
                ('conducting_body', models.CharField(max_length=200)),
                ('eligibility', models.TextField(help_text='Age, education, nationality etc.')),
                ('syllabus', models.TextField()),
                ('official_link', models.URLField(blank=True, null=True)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('notification', 'Notification'), ('application_start', 'Application Start'), ('application_end', 'Application End'), ('exam', 'Exam Date'), ('result', 'Result Date')], max_length=50)),
                ('date', models.DateField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='exams.exam')),
            ],
        ),
    ]
