# Generated by Django 6.0.4 on 2026-05-19 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_category_exam_application_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Set to True by admin to publish this user-submitted exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
