# Generated by Django 6.0.3 on 2026-03-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Link'), ('article', 'Article Link')], max_length=50)),
                ('url', models.URLField(help_text='Link to the PDF, video or article', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='exams.exam')),
            ],
        ),
    ]
