# Generated by Django 6.0.4 on 2026-05-19 11:36

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_description_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF or video file directly', null=True, upload_to=resources.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Link / File'), ('article', 'Article Link')], max_length=50),
        ),
    ]
