# Generated by Django 6.0.4 on 2026-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_file_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Subject/topic tag for AI matching', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this resource was viewed'),
        ),
    ]
