# Generated by Django 6.0.3 on 2026-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
